# Generated by Django 3.1.8 on 2021-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210416_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
